#Seperate new tweets with comma ","
tweets = [
    "Ekrem Bey'in de ifade ettiği gibi seçim kaybedilmiştir. @kilicdarogluk #Kılıçdaroğluİstifa https://twitter.com/sadevatandasyt/status/1663132437067563010/video/1",
    "Bu dava sizsiz de olur @kilicdarogluk #Kılıçdaroğluİstifa",
    "Elinizden geleni yapmak yetmiyorsa elinden daha fazlası gelene bırakmak lazım @kilicdarogluk #Kılıçdaroğluİstifa",
    "Gençlerden bir 5 yıl daha aldınız! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Anadoluda isminiz karşılık bulmuyor! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Kazanılmış seçimi elinizle hediye ettiniz! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Seçmeninizin oyunu barajı aşamayacak partilere hediye ettiniz! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Çevrenizdeki şakşakçılar ile birlikte ayrılın lütfen. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Aynı şeyleri yaparak farklı sonuçlar elde edemezsiniz! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Artık tıpış tıpış oy vermek yok! Yerel seçimleri de kaybetmeyin. @kilicdarogluk #Kılıçdaroğluİstifa",
    "25 milyon oyun sahibi siz değilsiniz. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Rakibiniz CHP'nin başında bulunduğunuz sürece işinin kolay olduğunu düşünüyor. @kilicdarogluk #Kılıçdaroğluİstifa",
    "İnsanlara içi boş umut satmaktan vazgeçin lütfen. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Aday olmamanızı istemiştik @kilicdarogluk #Kılıçdaroğluİstifa https://twitter.com/i/status/1662870198326575105/video/1",
    "Hakkımı helal etmiyorum! @kilicdarogluk #Kılıçdaroğluİstifa",
    "40 mv verirseniz masa sizi destekler. Bize sadece boş umut verdiğiniz için biz desteklemiyoruz. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Seçimin kaybının nedeni sizsiniz. Günah keçisi aramaya gerek yok. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Adamı kazandırdınız @kilicdarogluk #Kılıçdaroğluİstifa",
    "Doğru aday değildiniz, doğru aday değilsiniz, doğru aday olmayacaksınız. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Başarısız olan gitmelidir! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Partide gerçekten emek verenlerin emeğini hiçe saymayın! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Tarihe kötü şekilde geçmektense zamanında ayrılmak gerek! Zamanınız geçiyor. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Torun sevin lütfen. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Lütfen siyaseti gençlere bırakın! @kilicdarogluk #Kılıçdaroğluİstifa",
    "Parti içerisinden bir kişi elbette bu işi yapabilir. Vazgeçilmez olamazsınız @kilicdarogluk #Kılıçdaroğluİstifa",
    "Maç kaybedildiğinde taraftar değil hoca hesap verir. @kilicdarogluk #Kılıçdaroğluİstifa",
    "Tarihe bu şekilde geçmeyin. @kilicdarogluk #Kılıçdaroğluİstifa https://twitter.com/seckincelik33/status/1662860950792282114/video/1",

]
